### ISSUE TITLE
Tone Analyzer endpoint service in chatbots

### ISSUE THREAD

**Issue by casadosanti** [watson-developer-cloud/food-coach#15]
Hello. 
I thought this chatbot was consuming Analyzer's customer engagement service, with this possible tones:
sad
frustrated
satisfied
excited
polite
impolite
sympathetic

But I have made some tests and realize that the endpoint which is coumed is the general puspose one, that works with this tones:
Anger
Disgust
Fear
Joy
Sadness

Is there any way to connect this chatbot prototype to the customer engagement endpoint, equivalent to https://customer-engagement-demo.mybluemix.net/ ??

Thanks!

**Comment by germanattanasio** [comment]
You can connect this chatbot by using the `tone_chat` endpoint and sending the utterance. 
Take a look at the [API Reference](https://www.ibm.com/watson/developercloud/tone-analyzer/api/v3/node.html?node#tone-chat) where you can find a code snippet for this.
