### ISSUE TITLE
Add GDPR Language to Stand Alone Demo Pages

### ISSUE THREAD

**Issue by richieverma** [watson-developer-cloud/food-coach#22]
Context:
GDPR will go into effect on May 25th; we need the demos to display the following language in order to make them compliant with the law:

This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.

For more information see: https://github.ibm.com/Watson/developer-experience/issues/4342

**Comment by germanattanasio** [comment]
@richieverma can you add analytics like I did here: https://github.com/watson-developer-cloud/assistant-simple/commit/5b22075fdda2e271306d6f39c5317f32164a2c07

**Comment by richieverma** [comment]
@germanattanasio Added analytics
