### ISSUE TITLE
IAM APIKEY not provided

### ISSUE THREAD

**Issue by jmponceIBM** [watson-developer-cloud/food-coach#28]
I am trying to deploy your example however am getting the below error when a message is sent from the UI and no response is received:

```
2018-07-30T14:01:42.08-0400 [APP/PROC/WEB/0]OUT   "message": "{\"context\":{\"r
questId\":\"4062801983\",\"requestType\":\"incoming.Identity_Token\",\"userAgen
\":\"watson-developer-cloud-nodejs-3.7.0;\",\"clientIp\":\"169.47.199.81\",\"ur
\":\"https://iam-id-2.ng.bluemix.net\",\"instanceId\":\"iamid-788c86fd5c-c8d94\
,\"threadId\":\"42055\",\"host\":\"iamid-788c86fd5c-c8d94\",\"startTime\":\"30.
7.2018 18:01:41:962 UTC\",\"endTime\":\"30.07.2018 18:01:42:027 UTC\",\"elapsed
ime\":\"65\",\"locale\":\"en_US\",\"clusterName\":\"iam-id-prdal12-8brn\"},\"er
orCode\":\"BXNIM0415E\",\"errorMessage\":\"Provided API key could not be found\
}",
```

I know the instructions say to add a IAM API KEY from the Assistant and Tone Analyzer services' credentials tab, however my services aren't providing a IAM API KEY just username, password and url.  Is there some way to get this to run without having to provide these keys?

**Comment by germanattanasio** [comment]
The README describes what you are asking

<img src="https://user-images.githubusercontent.com/313157/43419547-d77fb9b8-9449-11e8-9f34-93f1cc6a54b8.png">
