### ISSUE TITLE
Food-coach sample fails to start.

### ISSUE THREAD

**Issue by LTepliakov** [watson-developer-cloud/food-coach#29]
Hello team.
I have got a problem deploying this sample application to ibm cloud.

When i do 
ibmcloud app push
I can see that application is built successfully, but it fails to start.
Below is error log.
[leon-food-coach.log](https://github.com/watson-developer-cloud/food-coach/files/2383195/leon-food-coach.log)

I am very new to ibm cloud and to java programming, so I would be very glad to get any hint how to move it forward.

**Comment by germanattanasio** [comment]
Remove the following variables from your `.env` file

```
CLOUDANT_URL
LOG_USER
LOG_PASS
```

**Comment by LTepliakov** [comment]
Thank you very much German! It resolved my problem.
